# Generated by Django 4.2.3 on 2024-04-19 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0011_alter_user_anh_dai_dien'),
        ('Transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giaodich',
            name='create_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='giaodich',
            name='dia_chi_lam_viec',
            field=models.CharField(default='Hồ Chí Minh', max_length=200),
        ),
        migrations.AddField(
            model_name='giaodich',
            name='ghi_chu',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='giaodich',
            name='gia_tri',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='giaodich',
            name='hinh_thuc_thanh_toan',
            field=models.CharField(default='Thu tiền tại nhà', max_length=20),
        ),
        migrations.AddField(
            model_name='giaodich',
            name='khach_hang_thue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.khachhang'),
        ),
        migrations.AddField(
            model_name='giaodich',
            name='loai_giao_dich',
            field=models.CharField(choices=[('single', 'Dùng lẻ'), ('rental', 'Từ bài đăng tìm việc'), ('booking', 'Từ bài thuê')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='giaodich',
            name='nhan_vien_thuc_hien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nhan_vien_lam', to='Authentication.khachhang'),
        ),
        migrations.AlterField(
            model_name='giaodich',
            name='trang_thai',
            field=models.CharField(choices=[('waiting', 'Chờ xác nhận'), ('process', 'Đang tiến hành'), ('successful', 'Thành công'), ('cancel', 'Hủy bỏ')], default='waiting', max_length=20),
        ),
    ]
