# Generated by Django 4.2.3 on 2024-04-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0002_giaodich_create_at_giaodich_dia_chi_lam_viec_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giaodich',
            name='thoi_gian',
        ),
        migrations.AddField(
            model_name='giaodich',
            name='thoi_gian_lam_viec',
            field=models.DateTimeField(null=True),
        ),
    ]
