# Generated by Django 4.2.3 on 2024-04-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0003_remove_giaodich_thoi_gian_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giaodich',
            name='thoi_gian_lam_viec',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='ChiTietGiaoDich',
        ),
    ]
