# Generated by Django 4.2.3 on 2024-02-28 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Rental', '0001_initial'),
        ('Booking', '0001_initial'),
        ('General', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('waiting', 'Chờ xác nhận'), ('successful', 'Thành công'), ('failed', 'Thất bại')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Booking.bookingpost')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rental.brand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rental.model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.vehicle')),
                ('vehicle_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='General.vehiclestatus')),
            ],
        ),
    ]
