# Generated by Django 4.2.3 on 2024-02-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bidding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='vehicle_status',
        ),
    ]
