# Generated by Django 4.2.3 on 2024-03-01 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_khachhang'),
        ('Bidding', '0002_remove_proposal_vehicle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='booking_post',
            new_name='bai_thue',
        ),
        migrations.RenameField(
            model_name='proposal',
            old_name='price',
            new_name='gia',
        ),
        migrations.RenameField(
            model_name='proposal',
            old_name='created_at',
            new_name='ngay_khoi_tao',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='model',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='status',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='user',
        ),
        migrations.AddField(
            model_name='proposal',
            name='khach_hang',
            field=models.ForeignKey(default=45454545, on_delete=django.db.models.deletion.CASCADE, to='Authentication.khachhang'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='trang_thai',
            field=models.CharField(choices=[('waiting', 'Chờ xác nhận'), ('process', 'đang tiến hành'), ('successful', 'Thành công'), ('failed', 'Thất bại')], default='waiting', max_length=20),
        ),
    ]
