# Generated by Django 4.2.3 on 2024-03-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bidding', '0003_rename_booking_post_proposal_bai_thue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
