# Generated by Django 4.2.3 on 2024-03-01 13:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_khachhang'),
        ('Bidding', '0004_alter_proposal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='khach_hang',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='Authentication.khachhang'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='trang_thai',
            field=models.CharField(choices=[('waiting', 'Chờ xác nhận'), ('process', 'Đang tiến hành'), ('successful', 'Thành công'), ('failed', 'Thất bại')], default='waiting', max_length=20),
        ),
    ]
