# Generated by Django 4.2.3 on 2024-02-28 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import functools
import ultis.helper
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('General', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='RentalPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('rent', 'Đang cho thuê'), ('ready', 'Sẵn sàng')], default='ready', max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('num_of_people', models.PositiveIntegerField()),
                ('allows_pet', models.BooleanField()),
                ('sub_service', models.CharField(max_length=200)),
                ('image_desc1', models.ImageField(default='/', upload_to=functools.partial(ultis.helper.custom_user_image_path, *(), **{'path': 'rental'}))),
                ('image_desc2', models.ImageField(default='/', upload_to=functools.partial(ultis.helper.custom_user_image_path, *(), **{'path': 'rental'}))),
                ('image_desc3', models.ImageField(default='/', upload_to=functools.partial(ultis.helper.custom_user_image_path, *(), **{'path': 'rental'}))),
                ('image_desc4', models.ImageField(default='/', upload_to=functools.partial(ultis.helper.custom_user_image_path, *(), **{'path': 'rental'}))),
                ('image_desc5', models.ImageField(default='/', upload_to=functools.partial(ultis.helper.custom_user_image_path, *(), **{'path': 'rental'}))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=150)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rental.brand')),
            ],
        ),
    ]
