# Generated by Django 4.2.3 on 2024-02-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0002_rename_details_rentalpost_chi_tiet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalpost',
            name='vehicle',
        ),
    ]
