# Generated by Django 4.2.3 on 2024-03-01 08:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Rental', '0003_remove_rentalpost_vehicle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RentalPost',
            new_name='BaiTimViec',
        ),
    ]
