# Generated by Django 4.2.3 on 2024-03-01 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_khachhang'),
        ('Bidding', '0003_rename_booking_post_proposal_bai_thue_and_more'),
        ('Rental', '0004_rename_rentalpost_baitimviec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baitimviec',
            name='model',
        ),
        migrations.RemoveField(
            model_name='baitimviec',
            name='user',
        ),
        migrations.AddField(
            model_name='baitimviec',
            name='khach_hang',
            field=models.ForeignKey(default=454, on_delete=django.db.models.deletion.CASCADE, to='Authentication.khachhang'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Model',
        ),
    ]
