# Generated by Django 4.2.3 on 2024-03-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0006_delete_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baitimviec',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='baitimviec',
            name='num_of_people',
        ),
    ]
