# Generated by Django 4.2.3 on 2024-04-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0007_remove_baitimviec_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baitimviec',
            name='da_duyet',
            field=models.BooleanField(default=False),
        ),
    ]
