# Generated by Django 4.2.3 on 2024-04-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0008_baitimviec_da_duyet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baitimviec',
            old_name='khach_hang',
            new_name='khach_hang_id',
        ),
    ]
