# Generated by Django 4.2.3 on 2024-02-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bidding', '0002_remove_proposal_vehicle_and_more'),
        ('Rental', '0003_remove_rentalpost_vehicle'),
        ('General', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.DeleteModel(
            name='VehicleStatus',
        ),
    ]
