# Generated by Django 4.2.3 on 2024-03-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0002_delete_location_delete_vehicle_delete_vehiclestatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demand',
        ),
    ]
