# Generated by Django 4.2.3 on 2024-02-28 09:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDoc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.TextField(choices=[('base', 'Chung'), ('about', 'Giới thiệu'), ('terms', 'Điều khoản')], default='base', max_length=100)),
                ('position', models.IntegerField(default=1)),
            ],
        ),
    ]
