# Generated by Django 4.2.3 on 2024-02-28 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HopDong',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cong_ty', models.CharField(max_length=100)),
                ('ngay_ky', models.DateField()),
                ('ngay_het_han', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nguoi_lao_dong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
