# Generated by Django 4.2.3 on 2024-02-29 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0002_hopdong'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydoc',
            old_name='type',
            new_name='loai',
        ),
        migrations.RenameField(
            model_name='companydoc',
            old_name='description',
            new_name='mo_ta',
        ),
        migrations.RenameField(
            model_name='companydoc',
            old_name='title',
            new_name='tieu_de',
        ),
    ]
