# Generated by Django 4.2.3 on 2024-02-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0003_rename_type_companydoc_loai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hopdong',
            name='anh_hop_dong',
            field=models.ImageField(default='1', upload_to=''),
        ),
    ]
