# Generated by Django 4.2.3 on 2024-02-29 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_khachhang'),
        ('Document', '0004_hopdong_anh_hop_dong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopdong',
            name='nguoi_lao_dong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.khachhang'),
        ),
    ]
