# Generated by Django 4.2.3 on 2024-03-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0005_alter_hopdong_nguoi_lao_dong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopdong',
            name='anh_hop_dong',
            field=models.ImageField(default='14', upload_to=''),
        ),
    ]
