# Generated by Django 4.2.3 on 2024-03-01 17:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0006_alter_hopdong_anh_hop_dong'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanGia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loi_nhuan', models.DecimalField(decimal_places=2, default=30, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DichVu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ten_dich_vu', models.CharField(max_length=200)),
                ('don_gia', models.PositiveIntegerField()),
            ],
        ),
    ]
