# Generated by Django 4.2.3 on 2024-03-02 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0007_bangia_dichvu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BanGia',
            new_name='BangGia',
        ),
    ]
