# Generated by Django 4.2.3 on 2024-04-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0008_rename_bangia_banggia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BangGia',
        ),
    ]
