# Generated by Django 4.2.3 on 2024-04-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0009_delete_banggia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DichVu',
        ),
    ]
