# Generated by Django 4.2.3 on 2024-02-29 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_rename_back_id_image_user_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='gender',
            new_name='gioi_tinh',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='ho_ten',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='date_of_birth',
            new_name='ngay_sinh',
        ),
        migrations.RenameField(
            model_name='userreview',
            old_name='rating',
            new_name='danh_gia',
        ),
        migrations.RenameField(
            model_name='userreview',
            old_name='created_at',
            new_name='ngay_tao',
        ),
        migrations.RenameField(
            model_name='userreview',
            old_name='feedback',
            new_name='nhan_xet',
        ),
        migrations.RemoveField(
            model_name='user',
            name='account_type',
        ),
    ]
