# Generated by Django 4.2.3 on 2024-02-29 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_rename_gender_user_gioi_tinh_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar',
            new_name='anh_dai_dien',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='hometown',
            new_name='dia_chi',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='date_issued',
            new_name='ngay_khoi_tao',
        ),
        migrations.RemoveField(
            model_name='user',
            name='doc_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='user',
            name='permanent_address',
        ),
    ]
