# Generated by Django 4.2.3 on 2024-02-29 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_nhanvien'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ma_khach_hang', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('Authentication.user',),
        ),
    ]
