# Generated by Django 4.2.3 on 2024-03-01 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_khachhang_idkh_nhanvien_idnv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='points',
        ),
        migrations.RemoveField(
            model_name='userreview',
            name='user',
        ),
        migrations.AddField(
            model_name='userreview',
            name='cho_khach_hang',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='user_nhan_reviews', to='Authentication.khachhang'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreview',
            name='cua_khach_hang',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to='Authentication.khachhang'),
            preserve_default=False,
        ),
    ]
