# Generated by Django 4.2.3 on 2024-04-10 09:55

from django.db import migrations, models
import functools
import ultis.helper


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0008_remove_user_points_remove_userreview_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='anh_dai_dien',
            field=models.ImageField(default='https://res.cloudinary.com/dtwy0ch1a/image/upload/v1712333902/avatarDefault.png', upload_to=functools.partial(ultis.helper.custom_user_image_path, *(), **{'path': 'avatar'})),
        ),
    ]
