# Generated by Django 4.2.3 on 2024-04-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0009_alter_user_anh_dai_dien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='anh_dai_dien',
            field=models.ImageField(default='https://res.cloudinary.com/dtwy0ch1a/image/upload/v1712333902/avatarDefault.png', upload_to=''),
        ),
    ]
