# Generated by Django 4.2.3 on 2024-02-29 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_read',
            new_name='da_doc',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='created_at',
            new_name='ngay_tao',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='body',
            new_name='noi_dung',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='title',
            new_name='tieu_de',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='typenoti',
            new_name='type_noti',
        ),
    ]
