# Generated by Django 4.2.3 on 2024-04-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0003_notification_danhcho'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='danhcho',
            new_name='loai',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='content_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='index',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='route',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type_noti',
        ),
        migrations.AddField(
            model_name='notification',
            name='mota_ngan',
            field=models.TextField(default=2, max_length=80),
            preserve_default=False,
        ),
    ]
