# Generated by Django 4.2.3 on 2024-04-19 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0011_alter_user_anh_dai_dien'),
        ('Notification', '0005_alter_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='loai',
            field=models.TextField(default='All', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Authentication.khachhang'),
        ),
    ]
