# Generated by Django 4.2.3 on 2024-02-28 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('demand', models.CharField(blank=True, max_length=100)),
                ('detail', models.TextField()),
                ('status', models.CharField(choices=[('waiting', 'Chờ báo giá'), ('cancel', 'Hủy bỏ'), ('approved', 'Đã xác nhận')], default='waiting', max_length=20)),
                ('start_date', models.DateField()),
                ('departure', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
