# Generated by Django 4.2.3 on 2024-02-29 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingpost',
            old_name='detail',
            new_name='chi_tiet',
        ),
        migrations.RenameField(
            model_name='bookingpost',
            old_name='title',
            new_name='tieu_de',
        ),
        migrations.RenameField(
            model_name='bookingpost',
            old_name='status',
            new_name='trang_thai',
        ),
    ]
