# Generated by Django 4.2.3 on 2024-03-01 08:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bidding', '0002_remove_proposal_vehicle_and_more'),
        ('Booking', '0002_rename_detail_bookingpost_chi_tiet_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingPost',
            new_name='BaiThue',
        ),
    ]
