# Generated by Django 4.2.3 on 2024-03-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_remove_baithue_user_baithue_khach_hang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baithue',
            old_name='demand',
            new_name='yeu_cau',
        ),
    ]
