# Generated by Django 4.2.3 on 2024-04-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_rename_demand_baithue_yeu_cau'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baithue',
            old_name='price',
            new_name='gia',
        ),
        migrations.RenameField(
            model_name='baithue',
            old_name='yeu_cau',
            new_name='mo_ta_ngan',
        ),
        migrations.RenameField(
            model_name='baithue',
            old_name='start_date',
            new_name='thoi_gian',
        ),
        migrations.RemoveField(
            model_name='baithue',
            name='departure',
        ),
        migrations.AlterField(
            model_name='baithue',
            name='trang_thai',
            field=models.CharField(choices=[('waiting', 'Chờ Xác Nhận'), ('processing', 'Đang Tiến Hành'), ('cancel', 'Hủy Bỏ'), ('done', 'Thành Công')], default='waiting', max_length=20),
        ),
    ]
