# Generated by Django 4.2.3 on 2024-04-10 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0006_rename_price_baithue_gia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baithue',
            old_name='khach_hang',
            new_name='khach_hang_id',
        ),
    ]
