# Generated by Django 4.2.3 on 2024-04-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0007_rename_khach_hang_baithue_khach_hang_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='baithue',
            name='da_duyet',
            field=models.BooleanField(default=False),
        ),
    ]
