# Generated by Django 4.2.3 on 2024-04-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0008_baithue_da_duyet'),
    ]

    operations = [
        migrations.AddField(
            model_name='baithue',
            name='khu_vuc',
            field=models.CharField(default='Hồ Chí Minh', max_length=100),
        ),
    ]
