# Generated by Django 4.2.3 on 2024-04-12 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0009_baithue_khu_vuc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baithue',
            old_name='khu_vuc',
            new_name='dia_chi',
        ),
    ]
